# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(961, 766)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.excelButton = QtWidgets.QPushButton(self.centralwidget)
        self.excelButton.setGeometry(QtCore.QRect(490, 690, 451, 31))
        self.excelButton.setObjectName("excelButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(490, 120, 451, 561))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 447, 524))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.imageView_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imageView_2.setGeometry(QtCore.QRect(9, 9, 421, 521))
        self.imageView_2.setText("")
        self.imageView_2.setObjectName("imageView_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.detButton = QtWidgets.QPushButton(self.widget)
        self.detButton.setObjectName("detButton")
        self.horizontalLayout.addWidget(self.detButton)
        self.recButton = QtWidgets.QPushButton(self.widget)
        self.recButton.setObjectName("recButton")
        self.horizontalLayout.addWidget(self.recButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 120, 441, 561))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imageView = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageView.sizePolicy().hasHeightForWidth())
        self.imageView.setSizePolicy(sizePolicy)
        self.imageView.setText("")
        self.imageView.setObjectName("imageView")
        self.verticalLayout_2.addWidget(self.imageView)
        self.recogButton = QtWidgets.QPushButton(self.widget1)
        self.recogButton.setObjectName("recogButton")
        self.verticalLayout_2.addWidget(self.recogButton)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(16, 16, 941, 91))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pathLabel = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setObjectName("pathLabel")
        self.verticalLayout_4.addWidget(self.pathLabel)
        self.pathLabel_2 = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel_2.sizePolicy().hasHeightForWidth())
        self.pathLabel_2.setSizePolicy(sizePolicy)
        self.pathLabel_2.setObjectName("pathLabel_2")
        self.verticalLayout_4.addWidget(self.pathLabel_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.inputPath = QtWidgets.QTextEdit(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPath.sizePolicy().hasHeightForWidth())
        self.inputPath.setSizePolicy(sizePolicy)
        self.inputPath.setObjectName("inputPath")
        self.verticalLayout_3.addWidget(self.inputPath)
        self.inputPath_2 = QtWidgets.QTextEdit(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPath_2.sizePolicy().hasHeightForWidth())
        self.inputPath_2.setSizePolicy(sizePolicy)
        self.inputPath_2.setObjectName("inputPath_2")
        self.verticalLayout_3.addWidget(self.inputPath_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.loadButton = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout_5.addWidget(self.loadButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 22))
        self.menubar.setObjectName("menubar")
        self.menuMy_First_APP = QtWidgets.QMenu(self.menubar)
        self.menuMy_First_APP.setObjectName("menuMy_First_APP")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionINFO = QtWidgets.QAction(MainWindow)
        self.actionINFO.setObjectName("actionINFO")
        self.menuMy_First_APP.addSeparator()
        self.menuMy_First_APP.addSeparator()
        self.menuMy_First_APP.addSeparator()
        self.menuMy_First_APP.addAction(self.actionINFO)
        self.menubar.addAction(self.menuMy_First_APP.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.excelButton.setText(_translate("MainWindow", "Excel File"))
        self.detButton.setText(_translate("MainWindow", "Det Results"))
        self.recButton.setText(_translate("MainWindow", "Rec Results"))
        self.recogButton.setText(_translate("MainWindow", "Recognition"))
        self.pathLabel.setText(_translate("MainWindow", "IMG Path"))
        self.pathLabel_2.setText(_translate("MainWindow", "RES Path"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.menuMy_First_APP.setTitle(_translate("MainWindow", "DocTable Recognition"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.actionINFO.setText(_translate("MainWindow", "INFO"))
