# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(843, 591)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 20, 771, 61))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pathLabel = QtWidgets.QLabel(self.widget)
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout_2.addWidget(self.pathLabel, 0, 0, 1, 1)
        self.inputPath = QtWidgets.QTextEdit(self.widget)
        self.inputPath.setObjectName("inputPath")
        self.gridLayout_2.addWidget(self.inputPath, 0, 1, 1, 1)
        self.pathLabel_2 = QtWidgets.QLabel(self.widget)
        self.pathLabel_2.setObjectName("pathLabel_2")
        self.gridLayout_2.addWidget(self.pathLabel_2, 1, 0, 1, 1)
        self.inputPath_2 = QtWidgets.QTextEdit(self.widget)
        self.inputPath_2.setObjectName("inputPath_2")
        self.gridLayout_2.addWidget(self.inputPath_2, 1, 1, 1, 1)
        self.loadButton = QtWidgets.QPushButton(self.widget)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout_2.addWidget(self.loadButton, 1, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(50, 90, 351, 451))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageView = QtWidgets.QLabel(self.widget1)
        self.imageView.setText("")
        self.imageView.setObjectName("imageView")
        self.verticalLayout.addWidget(self.imageView)
        self.recogButton = QtWidgets.QPushButton(self.widget1)
        self.recogButton.setObjectName("recogButton")
        self.verticalLayout.addWidget(self.recogButton)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(430, 90, 371, 451))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.widget2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 367, 416))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.imageView_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.imageView_2.setText("")
        self.imageView_2.setObjectName("imageView_2")
        self.gridLayout.addWidget(self.imageView_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 2)
        self.detButton = QtWidgets.QPushButton(self.widget2)
        self.detButton.setObjectName("detButton")
        self.gridLayout_3.addWidget(self.detButton, 1, 0, 1, 1)
        self.recButton = QtWidgets.QPushButton(self.widget2)
        self.recButton.setObjectName("recButton")
        self.gridLayout_3.addWidget(self.recButton, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 22))
        self.menubar.setObjectName("menubar")
        self.menuMy_First_APP = QtWidgets.QMenu(self.menubar)
        self.menuMy_First_APP.setObjectName("menuMy_First_APP")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionINFO = QtWidgets.QAction(MainWindow)
        self.actionINFO.setObjectName("actionINFO")
        self.menuMy_First_APP.addSeparator()
        self.menuMy_First_APP.addSeparator()
        self.menuMy_First_APP.addSeparator()
        self.menuMy_First_APP.addAction(self.actionINFO)
        self.menubar.addAction(self.menuMy_First_APP.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pathLabel.setText(_translate("MainWindow", "IMG Path"))
        self.pathLabel_2.setText(_translate("MainWindow", "RES Path"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.recogButton.setText(_translate("MainWindow", "Recognition"))
        self.detButton.setText(_translate("MainWindow", "Det Results"))
        self.recButton.setText(_translate("MainWindow", "Rec Results"))
        self.menuMy_First_APP.setTitle(_translate("MainWindow", "Menu"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.actionINFO.setText(_translate("MainWindow", "INFO"))
